# Generated by Django 4.1.7 on 2023-11-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='stage',
        ),
        migrations.AddField(
            model_name='plant',
            name='stages',
            field=models.ManyToManyField(related_name='stages', through='plants.PlantStage', to='plants.stage'),
        ),
        migrations.AlterField(
            model_name='plantstage',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantStages', to='plants.plant'),
        ),
        migrations.CreateModel(
            name='StagePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lights', models.FloatField(blank=True, null=True)),
                ('humididty', models.FloatField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='plants.stage')),
            ],
        ),
    ]
